### ISSUE TITLE
[Refactor] 전체 구조 리팩토링

### ISSUE THREAD

**Issue by moonkey48** [moonkey48/HeckDesign#1]
## ✏️ Summary

전체 구조 리팩토링 및 MVVM 패턴 적용

<br>

### 현재 HeckDesign에 있는 문제

> 다음 기능 구현 전에 아래의 문제들을 해결한 뒤 다음 기능 구현 예정입니다. 

1. MVVM 패턴이 적용되었지만 실제 사용한 것은 MV입니다. 하지만 MV 역시도 데이터 흐름이 명확하지 않고 Helper에 의존하는 등 문제들이 있어서 MVVM으로 명확히 적용해야 합니다.
2. Model이 sqlLite를 사용하고 있습니다. 하지만 CoreData로 쉽게 만들 수 있고 보다 가독성을 높이는 쪽으로 변경할 예정입니다. 
3. 폴더 구조가 명확하지 않습니다. 
4. 싱글톤을 남발하고 있습니다. 

<br>

## ✓ Todo
- [ ] MVVM 패턴 적용
- [ ] CoreData로 모델 활용 변경
- [ ] 폴더 구조 재배치
- [ ] 싱글톤, Helper 없애기

<br>
