### ISSUE TITLE
Feat : Issue 기능 구현

### ISSUE THREAD

**Issue by moonkey48** [moonkey48/HeckDesign#3]
## ✏️ Summary
Issue 기능 구현

<br>

## ✨ Description

> issue 탭을 기존의 heck과 nice가 헷갈릴 때 쓰는 기능이 아닌 다른 사람들과 디자인에 대해 공유할 수 있는 탭으로 구성하려 합니다. 해당 기능을 위해  Firebase Auth, Cloudinay, FireStore, Apple Login을 활용할 예정입니다.

<br>

## ✓ Todo
- [ ] IssueView 디자인
- [ ] IssueView Model 구현
- [ ] Apple Login, Firebase Auth 연결
- [ ] FireStore 연결
- [ ] Cloudinary 연결
- [ ] FireStore & Cloudinary 연결
